Support Arduino API
adafruit/Adafruit_LSM6DS pull request #21
Opened 2021-06-09 10:12 UTC by hathach

This PR add Arduino compatible API as https://github.com/arduino-libraries/Arduino_LSM6DSOX/blob/master/src/LSM6DSOX.h#L34

This allow for sketch that run on arduino sensonr/platform can be easily migrated to use with Adafruit Sensor (e.g https://experiments.withgoogle.com/tiny-motion-trainer)

```C
  // Arduino compatible API
  int readAcceleration(float &x, float &y, float &z);
  float accelerationSampleRate(void);
  int accelerationAvailable(void);

  int readGyroscope(float &x, float &y, float &z);
  float gyroscopeSampleRate(void);
  int gyroscopeAvailable(void);
```

PS: written fashion that requires https://github.com/adafruit/Adafruit_BusIO/pull/46, therefore this is submitted as draft for now

2021-06-09 10:50 UTC, hathach commented on Adafruit_LSM6DS.cpp
> +  setAccelRange(LSM6DS_ACCEL_RANGE_4_G);
Arduino official use Accel 4G and Gypro 2000 DPS across their IMU librraries. Setting it on init() to make sure the value returned from compatible API is matched with using Arduino lib (tested on actual hardware).

2021-06-21 05:07 UTC, ladyada requested changes

2021-06-21 05:07 UTC, ladyada commented on Adafruit_LSM6DS.cpp
> +  busio->setAddress(LSM6DS_WHOAMI);
plz revert :)

2021-06-21 05:07 UTC, ladyada commented on Adafruit_LSM6DS.cpp
> +  busio->setAddress(LSM6DS_STATUS_REG);
ditto

2021-06-21 05:21 UTC, hathach commented on Adafruit_LSM6DS.cpp
> +  busio->setAddress(LSM6DS_WHOAMI);
reverted :)

2021-06-21 05:21 UTC, hathach commented on Adafruit_LSM6DS.cpp
> +  busio->setAddress(LSM6DS_STATUS_REG);
done :)

2021-06-21 15:46 UTC, ladyada approved these changes

2021-06-21 16:08 UTC, hathach commented
thank you for your review

2021-06-21 16:08 UTC, merged